#!/bin/sh
xrandr --output DP-0 --primary --mode 2560x1080 --pos 1600x0 --rotate normal --output DP-1 --off --output HDMI-0 --off --output DP-2 --off --output DP-3 --off --output DP-4 --off --output DP-5 --mode 1600x900 --pos 0x0 --rotate normal
xrandr --dpi 95x92
