#!/bin/bash

cmd="$1"
val="$2"

case "$1" in
     set) amixer "$cmd" 'Master' "$val" ;;
     *)   amixer "$@" ;;
esac

volume=$(amixer sget Master | grep 'Right:' | awk -F'[][]' '{ print $2 }')
notify-send "Volume: $volume" -t 400
