#+TITLE Creatures / Characters and monsters of the Beyond Age rpg

* Lich of Priora

  Original name: WIP

  Dark Lich of priora is a human from before the fall of humanity, trapped in his grave by Kodesh and his evil experiments in black magic, corrupted by time and black energy
  the dark Lich rises, his goal is to restore his humanity through red magic

  Much of the lore for the Lich of Priora is found in the Grimoire of the dread alchimest Kodesh.

* Solomon of the Hecene

  Founder of the Hecenian empire, old empire that conquered the north contentant.
  Remnants of the empire formed the modern empire of Sidon

      A king larger then life, born from a poor family in a village of barbarians (Hetutus tribe),
  through ambission he rose through the ranks of the tribe to being the leader in training
  during a battle with their waring tribe <WIP>, solomon was captured,
  the tribe took him to their shaman where he was mentally tortured for years.
  Solomon found a way to withstand the mental torture by retreating into his head, he had time to think.
  The magic used to torture him created scaring, his mind unlocked a new dimension of power.
  using his new intelect he escaped and returned to his village and conquered the world.

  Much lore for solomon is found in the Musings of Solomon and other manuscripts <WIP>

* Leviathan

     Anchient creature from before the fall of man, lives within the ocean depths
     lore found in the book Iilmeth Ungol
