#!/bin/bash

# This is the list of bash aliases

alias ls='ls --color=auto'
alias v='$EDITOR'
alias vi='$EDITOR'
alias vim='$EDITOR'

alias gd='cd $HOME/Documents'
alias gdn='cd $HOME/Downloads'
alias gp='cd $HOME/Pictures'
alias gm='cd $HOME/Music'
alias gr='cd $HOME/Repos'


