#!/bin/bash
perc=$(ps -A -o pcpu | tail -n+2 | paste -sd+ | bc) 
border=2
height=$((20-$border*2))
pixels=$(echo "$perc $height" | awk '{print ($1/100.0)*$2}' )
pixels=$(printf "%.0f" "$pixels") 
y=$(($height-$pixels)) 
