#!/bin/bash

chosen=$(cut -d ';' -f1 ~/.config/scripts/emoji | dmenu -i -l 30 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

xdotool type "$chosen"
echo "$chosen" | tr -d '\n' | xclip -selection clipboard
notify-send "'$chosen' copied to clipboard." &
