#!/bin/bash

mpc_output=$(mpc)

final=$(echo "$mpc_output" | head -n -1)

first=$(echo "$final" | sed -n -e '1p')
second=$(echo "$final" | sed -n -e '2p')

[ -z "$first" ] && echo "Music Stopped" && exit 0

second_lines=$(echo "$second" | sed -s 's/ \+/ /g' | sed -s 's/\ /\n/g' | sed -e '2,3d' | tr '\n' ' ' | sed -s 's/paused/⏸/g' | sed -s 's/playing/▶/g')

final=$(echo "$first $second_lines")

echo "$final"

