#!/bin/bash

SINK="51"

function list_help() {
    echo "Syntax: music v +10, music v -10, music play, music pause, music stop, music info"
    exit 0
}

function wip() {
    echo "This feature is a work in progress..." 
    exit 0
}

case "$1" in
    "v" ) pactl set-sink-volume "$SINK" "$2%" ;;
    "play" ) ;;
    *) list_help ;;
esac
