#!/bin/bash

pushd () {
	command pushd "$@" > /dev/null
}

popd() {
	command popd "$@" > /dev/null
}

pushd $HOME
pdf=$(find -iname '*.pdf' -exec readlink -f {} \; | dmenu)
popd

[ -z "$pdf" ] && exit 0

zathura "$pdf"
