#!/bin/bash

PANELFIFO=/tmp/panel_fifo
CONFIG=~/.config/uniblocksrc
DEL=":::" 

#---------------------------------------
# Used for parsing modules into the fifo
#---------------------------------------
parse() {
    while read -r line; do
        sstring=${line#*,}
        script=${sstring%,*}
        tag=${line%%,*}
        interval=${line##*,}

        if [ "$tag" = W ]; then
            $script > "$PANELFIFO" &
        elif [ "$interval" = 0 ]; then
            $script | sed "s/^/$tag/" > "$PANELFIFO" &
        else
            while :; do
                $script | sed "s/^/$tag/"
                sleep "$interval"
            done > "$PANELFIFO" &
        fi
    done
}

trap 'kill -- -$$' INT

case $1 in
    --update | -u) [ -e "$PANELFIFO" ] && grep "^$2" $CONFIG | parse ;;
    * )
        [ -e "$PANELFIFO" ] && rm "$PANELFIFO" &&
            kill -9 $(pgrep -f "$0" | grep -v $$) 2> /dev/null
        mkfifo "$PANELFIFO"
        # ---------------------------------------
        # Parse the modules into the fifo
        # ---------------------------------------
        grep -Ev "^#|^$" $CONFIG | parse
        sleep 1

        while read -r line; do
            TAGS=$(awk -F, '/^\w/{print $1}' $CONFIG)
            #---------------------------------------
            # Parse moudles out from the fifo
            #---------------------------------------
            for tag in $TAGS; do
                case $line in
                    $tag*) echo "${line#$tag}" > /tmp/"$tag" ;;
                esac
            done

            #---------------------------------------
            # Print the result
            #---------------------------------------
            status=
            for tag in $TAGS; do
                if [ -z "$status" ]; then
                    read -r status < /tmp/"$tag"
                else
                    read -r newstatus < /tmp/"$tag"
                    status="$status $DEL $newstatus"
                fi
            done

            # xsetroot -name "$(printf "%s\r" "$status")"
            printf "%s%s%s%s\r" "%{S4}" "%{I}$status" "%{S0}" "%{I}$status" | lemonbar -f "Fira Code Retina" -f "monospace" -p -B#FF000000 -U#FFFFFFFF -u4 &

        done < "$PANELFIFO"
        ;;
esac

