#!/bin/bash

cmd="$1"
val="$2"

function get_volume() {
    amixer get Master | grep % |awk '{print $5}'| sed 's/[^0-9]//g'
}

function set_volume() { 
    amixer "$cmd" 'Master' "$val" 
    volume=$(amixer sget Master | grep 'Right:' | awk -F'[][]' '{ print $2 }')
    notify-send "Volume: $volume" -t 400
}

case "$1" in
     get) get_volume ;;
     set) get_volume ;;
esac

echo $(($(date +%s%N)/1000000))
