#!/bin/sh
xrandr --output DP-0 --off --output DP-1 --off --output HDMI-0 --primary --mode 2560x1080 --rate 85 --pos 0x0 --rotate normal --output DP-2 --off --output DP-3 --mode 1440x900 --pos 2560x180 --rotate normal --output DP-4 --off --output DP-5 --off
